# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosPessoais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('adress', models.CharField(max_length=100, verbose_name='Endereço')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('cep', models.CharField(max_length=100, verbose_name='Cep')),
                ('fhone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('mobile', models.CharField(max_length=20, verbose_name='Celular')),
                ('about', models.TextField(max_length=255, verbose_name='sobre')),
                ('data_nascimento', models.CharField(default='13 de julho de 1964', max_length=100, verbose_name='Data Nascimento')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('conhecimentos', models.TextField(verbose_name='Conhecimentos')),
                ('github', models.CharField(default='http://github.com/scarmarcos', max_length=100)),
                ('corrent_position', models.CharField(max_length=100, verbose_name='Cargo')),
                ('empresa', models.CharField(max_length=100, verbose_name='Empresa')),
            ],
        ),
    ]
